language: node_js

sudo: false

node_js:
  - "lts/*"

cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - test/node_modules

install:
  # install theme dependencies
  - yarn install --pure-lockfile
  - cd test
  # install test blog dependencies
  - yarn install --pure-lockfile
  - cd -

script:
  # build theme static files
  - npm run build
  # test generate hexo site
  - cd test
  # copy generated files to test folder
  - cp -R ../layout themes/amber/layout
  - cp -R ../source themes/amber/source
  - cp -R ../scripts themes/amber/scripts
  - cp ../_config.yml themes/amber/_config.yml
  # build test blog
  - npm run build
  - cd -

after_success:
  # package generated files
  - mkdir dist && cd dist
  - cp -R ../layout layout
  - cp -R ../source source
  - cp -R ../scripts scripts
  - cp ../_config.yml _config.yml
  - cp ../README.md README.md
  - cp ../README.zh-CN.md README.zh-CN.md
  - cp ../LICENSE LICENSE
  - cd -

deploy:
  provider: pages
  local-dir: dist
  target-branch: dist
  email: $GITHUB_EMAIL
  name: $GITHUB_NAME
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
